version: '2'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    container_name: redis
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --appendonly yes
    image: redis
    expose:
      - 6379
