version: '2'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
